//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.23 at 05:13:14 PM BRT 
//


package com.gapso.web.trieda.server.xml.input;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GrupoAlunoDemanda complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GrupoAlunoDemanda">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="AlunoDemanda" type="{}ItemAlunoDemanda"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GrupoAlunoDemanda", propOrder = {
    "alunoDemanda"
})
public class GrupoAlunoDemanda {

    @XmlElement(name = "AlunoDemanda")
    protected List<ItemAlunoDemanda> alunoDemanda;

    /**
     * Gets the value of the alunoDemanda property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the alunoDemanda property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAlunoDemanda().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ItemAlunoDemanda }
     * 
     * 
     */
    public List<ItemAlunoDemanda> getAlunoDemanda() {
        if (alunoDemanda == null) {
            alunoDemanda = new ArrayList<ItemAlunoDemanda>();
        }
        return this.alunoDemanda;
    }

}
