//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.23 at 05:21:16 PM BRT 
//


package com.gapso.web.trieda.server.xml.input;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.gapso.web.trieda.server.xml.output.GrupoAtendimentoOferta;


/**
 * <p>Java class for ItemAtendimentoHorarioAula complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ItemAtendimentoHorarioAula">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="horarioAulaId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="professorId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="virtual" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="creditoTeorico" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="atendimentosOfertas" type="{}GrupoAtendimentoOferta"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ItemAtendimentoHorarioAula", propOrder = {
    "horarioAulaId",
    "professorId",
    "virtual",
    "creditoTeorico",
    "atendimentosOfertas"
})
public class ItemAtendimentoHorarioAulaSolucao {

    protected int horarioAulaId;
    protected int professorId;
    protected boolean virtual;
    protected boolean creditoTeorico;
    @XmlElement(required = true)
    protected GrupoAtendimentoOfertaSolucao atendimentosOfertas;

    /**
     * Gets the value of the horarioAulaId property.
     * 
     */
    public int getHorarioAulaId() {
        return horarioAulaId;
    }

    /**
     * Sets the value of the horarioAulaId property.
     * 
     */
    public void setHorarioAulaId(int value) {
        this.horarioAulaId = value;
    }

    /**
     * Gets the value of the professorId property.
     * 
     */
    public int getProfessorId() {
        return professorId;
    }

    /**
     * Sets the value of the professorId property.
     * 
     */
    public void setProfessorId(int value) {
        this.professorId = value;
    }

    /**
     * Gets the value of the virtual property.
     * 
     */
    public boolean isVirtual() {
        return virtual;
    }

    /**
     * Sets the value of the virtual property.
     * 
     */
    public void setVirtual(boolean value) {
        this.virtual = value;
    }

    /**
     * Gets the value of the creditoTeorico property.
     * 
     */
    public boolean isCreditoTeorico() {
        return creditoTeorico;
    }

    /**
     * Sets the value of the creditoTeorico property.
     * 
     */
    public void setCreditoTeorico(boolean value) {
        this.creditoTeorico = value;
    }

    /**
     * Gets the value of the atendimentosOfertas property.
     * 
     * @return
     *     possible object is
     *     {@link GrupoAtendimentoOferta }
     *     
     */
    public GrupoAtendimentoOfertaSolucao getAtendimentosOfertas() {
        return atendimentosOfertas;
    }

    /**
     * Sets the value of the atendimentosOfertas property.
     * 
     * @param value
     *     allowed object is
     *     {@link GrupoAtendimentoOferta }
     *     
     */
    public void setAtendimentosOfertas(GrupoAtendimentoOfertaSolucao value) {
        this.atendimentosOfertas = value;
    }

}
