//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.08 at 11:18:45 AM BRST 
//


package com.gapso.web.trieda.server.xml.input;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ItemAtendimentoTaticoSolucao complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ItemAtendimentoTaticoSolucao">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="atendimentoOferta" type="{}ItemAtendimentoOfertaSolucao"/>
 *         &lt;element name="qtdeCreditosTeoricos" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="qtdeCreditosPraticos" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="fixaAbertura" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="fixaSala" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="fixaDia" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="fixaHorarios" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ItemAtendimentoTaticoSolucao", propOrder = {
    "atendimentoOferta",
    "qtdeCreditosTeoricos",
    "qtdeCreditosPraticos",
    "horariosAula",
    "fixaAbertura",
    "fixaSala",
    "fixaDia",
    "fixaHorarios"
})
public class ItemAtendimentoTaticoSolucao {

    @XmlElement(required = true)
    protected ItemAtendimentoOfertaSolucao atendimentoOferta;
    protected int qtdeCreditosTeoricos;
    protected int qtdeCreditosPraticos;
    protected GrupoIdentificador horariosAula;
    protected Boolean fixaAbertura;
    protected Boolean fixaSala;
    protected Boolean fixaDia;
    protected Boolean fixaHorarios;

    /**
     * Gets the value of the atendimentoOferta property.
     * 
     * @return
     *     possible object is
     *     {@link ItemAtendimentoOfertaSolucao }
     *     
     */
    public ItemAtendimentoOfertaSolucao getAtendimentoOferta() {
        return atendimentoOferta;
    }

    /**
     * Sets the value of the atendimentoOferta property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemAtendimentoOfertaSolucao }
     *     
     */
    public void setAtendimentoOferta(ItemAtendimentoOfertaSolucao value) {
        this.atendimentoOferta = value;
    }

    /**
     * Gets the value of the qtdeCreditosTeoricos property.
     * 
     */
    public int getQtdeCreditosTeoricos() {
        return qtdeCreditosTeoricos;
    }

    /**
     * Sets the value of the qtdeCreditosTeoricos property.
     * 
     */
    public void setQtdeCreditosTeoricos(int value) {
        this.qtdeCreditosTeoricos = value;
    }

    /**
     * Gets the value of the qtdeCreditosPraticos property.
     * 
     */
    public int getQtdeCreditosPraticos() {
        return qtdeCreditosPraticos;
    }

    /**
     * Sets the value of the qtdeCreditosPraticos property.
     * 
     */
    public void setQtdeCreditosPraticos(int value) {
        this.qtdeCreditosPraticos = value;
    }
    
    /**
     * Gets the value of the horarioAula property.
     * 
     * @return
     *     possible object is
     *     {@link GrupoIdentificador }
     *     
     */
    public GrupoIdentificador getHorariosAula() {
        return horariosAula;
    }

    /**
     * Sets the value of the horarioAula property.
     * 
     * @param value
     *     allowed object is
     *     {@link GrupoIdentificador }
     *     
     */
    public void setHorariosAula(GrupoIdentificador horariosAula) {
        this.horariosAula = horariosAula;
    }

    /**
     * Sets the value of the fixaAbertura property.
     * 
     */
    public void setFixaAbertura(Boolean value) {
        this.fixaAbertura = value;
    }

    /**
     * Gets the value of the fixaAbertura property.
     * 
     */
    public Boolean getFixaAbertura() {
        return fixaAbertura;
    }
    
    /**
     * Sets the value of the fixaSala property.
     * 
     */
    public void setFixaSala(Boolean value) {
        this.fixaSala = value;
    }

    /**
     * Gets the value of the fixaSala property.
     * 
     */
    public Boolean getFixaSala() {
        return fixaSala;
    }
    
    /**
     * Sets the value of the fixaDia property.
     * 
     */
    public void setFixaDia(Boolean value) {
        this.fixaSala = value;
    }

    /**
     * Gets the value of the fixaDia property.
     * 
     */
    public Boolean getFixaDia() {
        return fixaDia;
    }
    
    /**
     * Sets the value of the fixaHorarios property.
     * 
     */
    public void setFixaHorarios(Boolean value) {
        this.fixaHorarios = value;
    }

    /**
     * Gets the value of the fixaHorarios property.
     * 
     */
    public Boolean getFixaHorarios() {
        return fixaHorarios;
    }
}
