//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.08 at 11:18:45 AM BRST 
//


package com.gapso.web.trieda.server.xml.input;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ItemFixacao complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ItemFixacao">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="professorId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="disciplinaId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="salaId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="diaSemana" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="turnoId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="horarioAulaId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ItemFixacao", propOrder = {
    "id",
    "professorId",
    "disciplinaId",
    "turmaId",
    "campusId",
    "cenarioId",
    "instituicaoEnsinoId",
    "salaId",
    "horarios"
})
public class ItemFixacao {

    protected int id;
    protected Integer professorId;
    protected Integer disciplinaId;
    protected String turmaId;
    protected Integer campusId;
    protected Integer cenarioId;
    protected Integer instituicaoEnsinoId;
    protected Integer salaId;
    protected GrupoHorarioFixacao horarios;
    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the professorId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getProfessorId() {
        return professorId;
    }

    /**
     * Sets the value of the professorId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setProfessorId(Integer value) {
        this.professorId = value;
    }

    /**
     * Gets the value of the disciplinaId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDisciplinaId() {
        return disciplinaId;
    }

    /**
     * Sets the value of the disciplinaId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDisciplinaId(Integer value) {
        this.disciplinaId = value;
    }

    /**
     * Gets the value of the salaId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSalaId() {
        return salaId;
    }

    /**
     * Sets the value of the salaId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSalaId(Integer value) {
        this.salaId = value;
    }

	/**
	 * @return the turmaId
	 */
	public String getTurmaId()
	{
		return turmaId;
	}

	/**
	 * @param string the turmaId to set
	 */
	public void setTurmaId(String string)
	{
		this.turmaId = string;
	}

	/**
	 * @return the campusId
	 */
	public Integer getCampusId()
	{
		return campusId;
	}

	/**
	 * @param campusId the campusId to set
	 */
	public void setCampusId(Integer campusId)
	{
		this.campusId = campusId;
	}

	/**
	 * @return the cenarioId
	 */
	public Integer getCenarioId()
	{
		return cenarioId;
	}

	/**
	 * @param cenarioId the cenarioId to set
	 */
	public void setCenarioId(Integer cenarioId)
	{
		this.cenarioId = cenarioId;
	}

	/**
	 * @return the instituicaoEnsinoId
	 */
	public Integer getInstituicaoEnsinoId()
	{
		return instituicaoEnsinoId;
	}

	/**
	 * @param instituicaoEnsinoId the instituicaoEnsinoId to set
	 */
	public void setInstituicaoEnsinoId(Integer instituicaoEnsinoId)
	{
		this.instituicaoEnsinoId = instituicaoEnsinoId;
	}

	/**
	 * @return the horarios
	 */
	public GrupoHorarioFixacao getHorarios()
	{
		return horarios;
	}

	/**
	 * @param horarios the horarios to set
	 */
	public void setHorarios(GrupoHorarioFixacao horarios)
	{
		this.horarios = horarios;
	}

   

}
