//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.09 at 09:57:16 AM BRST 
//


package com.gapso.web.trieda.server.xml.input;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ItemAtendimentoDiaSemana complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ItemAtendimentoDiaSemana">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="diaSemana" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;choice>
 *           &lt;element name="atendimentosTatico" type="{}GrupoAtendimentoTatico"/>
 *           &lt;element name="atendimentosTurnos" type="{}GrupoAtendimentoTurno"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ItemAtendimentoDiaSemana", propOrder = {
    "diaSemana",
    "atendimentosTatico",
    "atendimentosTurnos"
})
public class ItemAtendimentoDiaSemana {

    protected int diaSemana;
    protected GrupoAtendimentoTatico atendimentosTatico;
    protected GrupoAtendimentoTurno atendimentosTurnos;

    /**
     * Gets the value of the diaSemana property.
     * 
     */
    public int getDiaSemana() {
        return diaSemana;
    }

    /**
     * Sets the value of the diaSemana property.
     * 
     */
    public void setDiaSemana(int value) {
        this.diaSemana = value;
    }

    /**
     * Gets the value of the atendimentosTatico property.
     * 
     * @return
     *     possible object is
     *     {@link GrupoAtendimentoTatico }
     *     
     */
    public GrupoAtendimentoTatico getAtendimentosTatico() {
        return atendimentosTatico;
    }

    /**
     * Sets the value of the atendimentosTatico property.
     * 
     * @param value
     *     allowed object is
     *     {@link GrupoAtendimentoTatico }
     *     
     */
    public void setAtendimentosTatico(GrupoAtendimentoTatico value) {
        this.atendimentosTatico = value;
    }

    /**
     * Gets the value of the atendimentosTurnos property.
     * 
     * @return
     *     possible object is
     *     {@link GrupoAtendimentoTurno }
     *     
     */
    public GrupoAtendimentoTurno getAtendimentosTurnos() {
        return atendimentosTurnos;
    }

    /**
     * Sets the value of the atendimentosTurnos property.
     * 
     * @param value
     *     allowed object is
     *     {@link GrupoAtendimentoTurno }
     *     
     */
    public void setAtendimentosTurnos(GrupoAtendimentoTurno value) {
        this.atendimentosTurnos = value;
    }

}
