//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.14 at 10:24:47 AM BRST 
//


package com.gapso.web.trieda.server.xml.input;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ItemParametrosPlanejamento complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ItemParametrosPlanejamento">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="niveisDificuldadeHorario" type="{}GrupoNivelDificuldadeHorario"/>
 *         &lt;element name="equilibrarDiversidadeDiscDia" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="minimizarDeslocProfessor" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="minimizarDeslocAluno" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="maxDeslocProfessor" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="maximizarAvaliacaoCursos" type="{}GrupoIdentificador"/>
 *         &lt;element name="minimizarCustoDocenteCursos" type="{}GrupoIdentificador"/>
 *         &lt;element name="permiteCompartilhamentoTurma" type="{}GrupoGrupo"/>
 *         &lt;element name="cargaHorariaSemanalAluno">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="equilibrar" type="{http://www.w3.org/2001/XMLSchema}anySimpleType"/>
 *                   &lt;element name="minimizarDias" type="{http://www.w3.org/2001/XMLSchema}anySimpleType"/>
 *                   &lt;element name="indiferente" type="{http://www.w3.org/2001/XMLSchema}anySimpleType"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="minimizarHorariosVaziosProfessor" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="minimizarDiasSemanaProfessor" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="desempenhoProfDisponibilidade" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="custoProfDisponibilidade" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="evitarReducaoCargaHorariaProf" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="evitarProfUltimoPrimeiroHor" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ItemParametrosPlanejamento", propOrder = {
    "niveisDificuldadeHorario",
    "equilibrarDiversidadeDiscDia",
    "minimizarDeslocProfessor",
    "minimizarDeslocAluno",
    "maxDeslocProfessor",
    "maximizarAvaliacaoCursos",
    "minimizarCustoDocenteCursos",
    "permiteCompartilhamentoTurma",
    "cargaHorariaSemanalAluno",
    "minimizarHorariosVaziosProfessor",
    "minimizarDiasSemanaProfessor",
    "desempenhoProfDisponibilidade",
    "custoProfDisponibilidade",
    "evitarReducaoCargaHorariaProf",
    "evitarProfUltimoPrimeiroHor"
})
public class ItemParametrosPlanejamento {

    @XmlElement(required = true)
    protected GrupoNivelDificuldadeHorario niveisDificuldadeHorario;
    protected boolean equilibrarDiversidadeDiscDia;
    protected boolean minimizarDeslocProfessor;
    protected boolean minimizarDeslocAluno;
    protected int maxDeslocProfessor;
    @XmlElement(required = true)
    protected GrupoIdentificador maximizarAvaliacaoCursos;
    @XmlElement(required = true)
    protected GrupoIdentificador minimizarCustoDocenteCursos;
    @XmlElement(required = true)
    protected GrupoGrupo permiteCompartilhamentoTurma;
    @XmlElement(required = true)
    protected ItemParametrosPlanejamento.CargaHorariaSemanalAluno cargaHorariaSemanalAluno;
    protected boolean minimizarHorariosVaziosProfessor;
    protected boolean minimizarDiasSemanaProfessor;
    protected boolean desempenhoProfDisponibilidade;
    protected boolean custoProfDisponibilidade;
    protected boolean evitarReducaoCargaHorariaProf;
    protected boolean evitarProfUltimoPrimeiroHor;

    /**
     * Gets the value of the niveisDificuldadeHorario property.
     * 
     * @return
     *     possible object is
     *     {@link GrupoNivelDificuldadeHorario }
     *     
     */
    public GrupoNivelDificuldadeHorario getNiveisDificuldadeHorario() {
        return niveisDificuldadeHorario;
    }

    /**
     * Sets the value of the niveisDificuldadeHorario property.
     * 
     * @param value
     *     allowed object is
     *     {@link GrupoNivelDificuldadeHorario }
     *     
     */
    public void setNiveisDificuldadeHorario(GrupoNivelDificuldadeHorario value) {
        this.niveisDificuldadeHorario = value;
    }

    /**
     * Gets the value of the equilibrarDiversidadeDiscDia property.
     * 
     */
    public boolean isEquilibrarDiversidadeDiscDia() {
        return equilibrarDiversidadeDiscDia;
    }

    /**
     * Sets the value of the equilibrarDiversidadeDiscDia property.
     * 
     */
    public void setEquilibrarDiversidadeDiscDia(boolean value) {
        this.equilibrarDiversidadeDiscDia = value;
    }

    /**
     * Gets the value of the minimizarDeslocProfessor property.
     * 
     */
    public boolean isMinimizarDeslocProfessor() {
        return minimizarDeslocProfessor;
    }

    /**
     * Sets the value of the minimizarDeslocProfessor property.
     * 
     */
    public void setMinimizarDeslocProfessor(boolean value) {
        this.minimizarDeslocProfessor = value;
    }

    /**
     * Gets the value of the minimizarDeslocAluno property.
     * 
     */
    public boolean isMinimizarDeslocAluno() {
        return minimizarDeslocAluno;
    }

    /**
     * Sets the value of the minimizarDeslocAluno property.
     * 
     */
    public void setMinimizarDeslocAluno(boolean value) {
        this.minimizarDeslocAluno = value;
    }

    /**
     * Gets the value of the maxDeslocProfessor property.
     * 
     */
    public int getMaxDeslocProfessor() {
        return maxDeslocProfessor;
    }

    /**
     * Sets the value of the maxDeslocProfessor property.
     * 
     */
    public void setMaxDeslocProfessor(int value) {
        this.maxDeslocProfessor = value;
    }

    /**
     * Gets the value of the maximizarAvaliacaoCursos property.
     * 
     * @return
     *     possible object is
     *     {@link GrupoIdentificador }
     *     
     */
    public GrupoIdentificador getMaximizarAvaliacaoCursos() {
        return maximizarAvaliacaoCursos;
    }

    /**
     * Sets the value of the maximizarAvaliacaoCursos property.
     * 
     * @param value
     *     allowed object is
     *     {@link GrupoIdentificador }
     *     
     */
    public void setMaximizarAvaliacaoCursos(GrupoIdentificador value) {
        this.maximizarAvaliacaoCursos = value;
    }

    /**
     * Gets the value of the minimizarCustoDocenteCursos property.
     * 
     * @return
     *     possible object is
     *     {@link GrupoIdentificador }
     *     
     */
    public GrupoIdentificador getMinimizarCustoDocenteCursos() {
        return minimizarCustoDocenteCursos;
    }

    /**
     * Sets the value of the minimizarCustoDocenteCursos property.
     * 
     * @param value
     *     allowed object is
     *     {@link GrupoIdentificador }
     *     
     */
    public void setMinimizarCustoDocenteCursos(GrupoIdentificador value) {
        this.minimizarCustoDocenteCursos = value;
    }

    /**
     * Gets the value of the permiteCompartilhamentoTurma property.
     * 
     * @return
     *     possible object is
     *     {@link GrupoGrupo }
     *     
     */
    public GrupoGrupo getPermiteCompartilhamentoTurma() {
        return permiteCompartilhamentoTurma;
    }

    /**
     * Sets the value of the permiteCompartilhamentoTurma property.
     * 
     * @param value
     *     allowed object is
     *     {@link GrupoGrupo }
     *     
     */
    public void setPermiteCompartilhamentoTurma(GrupoGrupo value) {
        this.permiteCompartilhamentoTurma = value;
    }

    /**
     * Gets the value of the cargaHorariaSemanalAluno property.
     * 
     * @return
     *     possible object is
     *     {@link ItemParametrosPlanejamento.CargaHorariaSemanalAluno }
     *     
     */
    public ItemParametrosPlanejamento.CargaHorariaSemanalAluno getCargaHorariaSemanalAluno() {
        return cargaHorariaSemanalAluno;
    }

    /**
     * Sets the value of the cargaHorariaSemanalAluno property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemParametrosPlanejamento.CargaHorariaSemanalAluno }
     *     
     */
    public void setCargaHorariaSemanalAluno(ItemParametrosPlanejamento.CargaHorariaSemanalAluno value) {
        this.cargaHorariaSemanalAluno = value;
    }

    /**
     * Gets the value of the minimizarHorariosVaziosProfessor property.
     * 
     */
    public boolean isMinimizarHorariosVaziosProfessor() {
        return minimizarHorariosVaziosProfessor;
    }

    /**
     * Sets the value of the minimizarHorariosVaziosProfessor property.
     * 
     */
    public void setMinimizarHorariosVaziosProfessor(boolean value) {
        this.minimizarHorariosVaziosProfessor = value;
    }

    /**
     * Gets the value of the minimizarDiasSemanaProfessor property.
     * 
     */
    public boolean isMinimizarDiasSemanaProfessor() {
        return minimizarDiasSemanaProfessor;
    }

    /**
     * Sets the value of the minimizarDiasSemanaProfessor property.
     * 
     */
    public void setMinimizarDiasSemanaProfessor(boolean value) {
        this.minimizarDiasSemanaProfessor = value;
    }

    /**
     * Gets the value of the desempenhoProfDisponibilidade property.
     * 
     */
    public boolean isDesempenhoProfDisponibilidade() {
        return desempenhoProfDisponibilidade;
    }

    /**
     * Sets the value of the desempenhoProfDisponibilidade property.
     * 
     */
    public void setDesempenhoProfDisponibilidade(boolean value) {
        this.desempenhoProfDisponibilidade = value;
    }

    /**
     * Gets the value of the custoProfDisponibilidade property.
     * 
     */
    public boolean isCustoProfDisponibilidade() {
        return custoProfDisponibilidade;
    }

    /**
     * Sets the value of the custoProfDisponibilidade property.
     * 
     */
    public void setCustoProfDisponibilidade(boolean value) {
        this.custoProfDisponibilidade = value;
    }

    /**
     * Gets the value of the evitarReducaoCargaHorariaProf property.
     * 
     */
    public boolean isEvitarReducaoCargaHorariaProf() {
        return evitarReducaoCargaHorariaProf;
    }

    /**
     * Sets the value of the evitarReducaoCargaHorariaProf property.
     * 
     */
    public void setEvitarReducaoCargaHorariaProf(boolean value) {
        this.evitarReducaoCargaHorariaProf = value;
    }

    /**
     * Gets the value of the evitarProfUltimoPrimeiroHor property.
     * 
     */
    public boolean isEvitarProfUltimoPrimeiroHor() {
        return evitarProfUltimoPrimeiroHor;
    }

    /**
     * Sets the value of the evitarProfUltimoPrimeiroHor property.
     * 
     */
    public void setEvitarProfUltimoPrimeiroHor(boolean value) {
        this.evitarProfUltimoPrimeiroHor = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="equilibrar" type="{http://www.w3.org/2001/XMLSchema}anySimpleType"/>
     *         &lt;element name="minimizarDias" type="{http://www.w3.org/2001/XMLSchema}anySimpleType"/>
     *         &lt;element name="indiferente" type="{http://www.w3.org/2001/XMLSchema}anySimpleType"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "equilibrar",
        "minimizarDias",
        "indiferente"
    })
    public static class CargaHorariaSemanalAluno {

        @XmlSchemaType(name = "anySimpleType")
        protected Object equilibrar;
        @XmlSchemaType(name = "anySimpleType")
        protected Object minimizarDias;
        @XmlSchemaType(name = "anySimpleType")
        protected Object indiferente;

        /**
         * Gets the value of the equilibrar property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getEquilibrar() {
            return equilibrar;
        }

        /**
         * Sets the value of the equilibrar property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setEquilibrar(Object value) {
            this.equilibrar = value;
        }

        /**
         * Gets the value of the minimizarDias property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getMinimizarDias() {
            return minimizarDias;
        }

        /**
         * Sets the value of the minimizarDias property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setMinimizarDias(Object value) {
            this.minimizarDias = value;
        }

        /**
         * Gets the value of the indiferente property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getIndiferente() {
            return indiferente;
        }

        /**
         * Sets the value of the indiferente property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setIndiferente(Object value) {
            this.indiferente = value;
        }

    }

}
