//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.08 at 11:18:45 AM BRST 
//


package com.gapso.web.trieda.server.xml.input;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ItemParametrosPlanejamento complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ItemParametrosPlanejamento">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="modoOtimizacao" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="otimizarPor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cargaHorariaSemanalAluno">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="equilibrar" type="{http://www.w3.org/2001/XMLSchema}anySimpleType"/>
 *                   &lt;element name="minimizarDias" type="{http://www.w3.org/2001/XMLSchema}anySimpleType"/>
 *                   &lt;element name="indiferente" type="{http://www.w3.org/2001/XMLSchema}anySimpleType"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="alunosMesmoPeriodoNaMesmaSala" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="permitirAlunosEmVariosCampi" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="minimizarDeslocAluno" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="cargaHorariaSemanalProfessor">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="equilibrar" type="{http://www.w3.org/2001/XMLSchema}anySimpleType"/>
 *                   &lt;element name="minimizarDias" type="{http://www.w3.org/2001/XMLSchema}anySimpleType"/>
 *                   &lt;element name="indiferente" type="{http://www.w3.org/2001/XMLSchema}anySimpleType"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="permitirProfessorEmVariosCampi" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="minimizarDeslocProfessor" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="maxDeslocProfessor" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="minimizarHorariosVaziosProfessor" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="evitarReducaoCargaHorariaProf" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="evitarReducaoCargaHorariaProfValor" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="evitarProfUltimoPrimeiroHor" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="evitarProfUltimoPrimeiroHorValor" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="11"/>
 *         &lt;element name="preferenciaProfessorDisciplina" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="desempenhoProfDisponibilidade" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="funcaoObjetivo" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="considerarEquivalencia" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="minAlunosAberturaTurmas" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="minAlunosAberturaTurmasValor" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="violarMinTurmasFormandos" type="{http://www.w3.org/2001/XMLSchema}boolean"/>         
 *         &lt;element name="niveisDificuldadeHorario" type="{}GrupoNivelDificuldadeHorario"/>
 *         &lt;element name="equilibrarDiversidadeDiscDia" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="regrasGenericasDivisaoCredito" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="regrasEspecificasDivisaoCredito" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="maximizarAvaliacaoCursosSel" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="maximizarAvaliacaoCursos" type="{}GrupoIdentificador" minOccurs="0"/>
 *         &lt;element name="minimizarCustoDocenteCursosSel" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="minimizarCustoDocenteCursos" type="{}GrupoIdentificador" minOccurs="0"/>
 *         &lt;element name="permiteCompartilhamentoTurmaSel" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="permiteCompartilhamentoTurma" type="{}GrupoGrupo" minOccurs="0"/>
 *         &lt;element name="percentuaisMinimoMestres" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="percentuaisMinimoDoutores" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="areaTitulacaoProfessorCurso" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="maximoDisciplinasDeUmProfessorPorCurso" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="custoProfDisponibilidade" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="utilizarDemandasP2" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="percentuaisMinimoParcialIntegral" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="percentuaisMinimoIntegral" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ItemParametrosPlanejamento", propOrder = {
    "modoOtimizacao",
    "otimizarPor",
    "cargaHorariaSemanalAluno",
    "alunosMesmoPeriodoNaMesmaSala",
    "permitirAlunosEmVariosCampi",
    "minimizarDeslocAluno",
    "cargaHorariaSemanalProfessor",
    "permitirProfessorEmVariosCampi",
    "minimizarDeslocProfessor",
    "maxDeslocProfessor",
    "minimizarHorariosVaziosProfessor",
    "evitarReducaoCargaHorariaProf",
    "evitarReducaoCargaHorariaProfValor",
    "evitarProfUltimoPrimeiroHor",
    "evitarProfUltimoPrimeiroHorValor",
    "preferenciaProfessorDisciplina",
    "desempenhoProfDisponibilidade",
    "funcaoObjetivo",
    "considerarEquivalencia",
    "minAlunosAberturaTurmas",
    "minAlunosAberturaTurmasValor",
    "violarMinTurmasFormandos",
    "niveisDificuldadeHorario",
    "equilibrarDiversidadeDiscDia",
    "regrasGenericasDivisaoCredito",
    "regrasEspecificasDivisaoCredito",
    "maximizarAvaliacaoCursosSel",
    "maximizarAvaliacaoCursos",
    "minimizarCustoDocenteCursosSel",
    "minimizarCustoDocenteCursos",
    "permiteCompartilhamentoTurmaSel",
    "permiteCompartilhamentoTurma",
    "percentuaisMinimoMestres",
    "percentuaisMinimoDoutores",
    "areaTitulacaoProfessorCurso",
    "maximoDisciplinasDeUmProfessorPorCurso",
    "custoProfDisponibilidade",
    "utilizarDemandasP2",
    "percentuaisMinimoParcialIntegral",
    "percentuaisMinimoIntegral"
})
public class ItemParametrosPlanejamento {

    @XmlElement(required = true)
    protected String modoOtimizacao;
    @XmlElement(required = true)
    protected String otimizarPor;
    @XmlElement(required = true)
    protected ItemParametrosPlanejamento.CargaHorariaSemanalAluno cargaHorariaSemanalAluno;
    protected boolean alunosMesmoPeriodoNaMesmaSala;
    protected boolean permitirAlunosEmVariosCampi;
    protected boolean minimizarDeslocAluno;
    @XmlElement(required = true)
    protected ItemParametrosPlanejamento.CargaHorariaSemanalProfessor cargaHorariaSemanalProfessor;
    protected boolean permitirProfessorEmVariosCampi;
    protected boolean minimizarDeslocProfessor;
    protected Integer maxDeslocProfessor;
    protected boolean minimizarHorariosVaziosProfessor;
    protected boolean evitarReducaoCargaHorariaProf;
    protected Integer evitarReducaoCargaHorariaProfValor;
    protected boolean evitarProfUltimoPrimeiroHor;
    protected Integer evitarProfUltimoPrimeiroHorValor;
    protected boolean preferenciaProfessorDisciplina;
    protected boolean desempenhoProfDisponibilidade;
    protected int funcaoObjetivo;
    protected boolean considerarEquivalencia;
    protected boolean minAlunosAberturaTurmas;
    protected Integer minAlunosAberturaTurmasValor;
    protected boolean violarMinTurmasFormandos;
    @XmlElement(required = true)
    protected GrupoNivelDificuldadeHorario niveisDificuldadeHorario;
    protected boolean equilibrarDiversidadeDiscDia;
    protected boolean regrasGenericasDivisaoCredito;
    protected boolean regrasEspecificasDivisaoCredito;
    protected boolean maximizarAvaliacaoCursosSel;
    protected GrupoIdentificador maximizarAvaliacaoCursos;
    protected boolean minimizarCustoDocenteCursosSel;
    protected GrupoIdentificador minimizarCustoDocenteCursos;
    protected boolean permiteCompartilhamentoTurmaSel;
    protected GrupoGrupo permiteCompartilhamentoTurma;
    protected boolean percentuaisMinimoMestres;
    protected boolean percentuaisMinimoDoutores;
    protected boolean areaTitulacaoProfessorCurso;
    protected boolean maximoDisciplinasDeUmProfessorPorCurso;
    protected boolean custoProfDisponibilidade;
    protected boolean utilizarDemandasP2;
    protected boolean percentuaisMinimoParcialIntegral;
    protected boolean percentuaisMinimoIntegral;

    /**
     * Gets the value of the modoOtimizacao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModoOtimizacao() {
        return modoOtimizacao;
    }

    /**
     * Sets the value of the modoOtimizacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModoOtimizacao(String value) {
        this.modoOtimizacao = value;
    }
    
    /**
     * Gets the value of the otimizarPor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtimizarPor() {
        return otimizarPor;
    }

    /**
     * Sets the value of the modoOtimizacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtimizarPor(String value) {
        this.otimizarPor = value;
    }

    /**
     * Gets the value of the cargaHorariaSemanalAluno property.
     * 
     * @return
     *     possible object is
     *     {@link ItemParametrosPlanejamento.CargaHorariaSemanalAluno }
     *     
     */
    public ItemParametrosPlanejamento.CargaHorariaSemanalAluno getCargaHorariaSemanalAluno() {
        return cargaHorariaSemanalAluno;
    }

    /**
     * Sets the value of the cargaHorariaSemanalAluno property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemParametrosPlanejamento.CargaHorariaSemanalAluno }
     *     
     */
    public void setCargaHorariaSemanalAluno(ItemParametrosPlanejamento.CargaHorariaSemanalAluno value) {
        this.cargaHorariaSemanalAluno = value;
    }

    /**
     * Gets the value of the alunosMesmoPeriodoNaMesmaSala property.
     * 
     */
    public boolean isAlunosMesmoPeriodoNaMesmaSala() {
        return alunosMesmoPeriodoNaMesmaSala;
    }

    /**
     * Sets the value of the alunosMesmoPeriodoNaMesmaSala property.
     * 
     */
    public void setAlunosMesmoPeriodoNaMesmaSala(boolean value) {
        this.alunosMesmoPeriodoNaMesmaSala = value;
    }

    /**
     * Gets the value of the permitirAlunosEmVariosCampi property.
     * 
     */
    public boolean isPermitirAlunosEmVariosCampi() {
        return permitirAlunosEmVariosCampi;
    }

    /**
     * Sets the value of the permitirAlunosEmVariosCampi property.
     * 
     */
    public void setPermitirAlunosEmVariosCampi(boolean value) {
        this.permitirAlunosEmVariosCampi = value;
    }

    /**
     * Gets the value of the minimizarDeslocAluno property.
     * 
     */
    public boolean isMinimizarDeslocAluno() {
        return minimizarDeslocAluno;
    }

    /**
     * Sets the value of the minimizarDeslocAluno property.
     * 
     */
    public void setMinimizarDeslocAluno(boolean value) {
        this.minimizarDeslocAluno = value;
    }

    /**
     * Gets the value of the cargaHorariaSemanalProfessor property.
     * 
     * @return
     *     possible object is
     *     {@link ItemParametrosPlanejamento.CargaHorariaSemanalProfessor }
     *     
     */
    public ItemParametrosPlanejamento.CargaHorariaSemanalProfessor getCargaHorariaSemanalProfessor() {
        return cargaHorariaSemanalProfessor;
    }

    /**
     * Sets the value of the cargaHorariaSemanalProfessor property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemParametrosPlanejamento.CargaHorariaSemanalProfessor }
     *     
     */
    public void setCargaHorariaSemanalProfessor(ItemParametrosPlanejamento.CargaHorariaSemanalProfessor value) {
        this.cargaHorariaSemanalProfessor = value;
    }

    /**
     * Gets the value of the permitirProfessorEmVariosCampi property.
     * 
     */
    public boolean isPermitirProfessorEmVariosCampi() {
        return permitirProfessorEmVariosCampi;
    }

    /**
     * Sets the value of the permitirProfessorEmVariosCampi property.
     * 
     */
    public void setPermitirProfessorEmVariosCampi(boolean value) {
        this.permitirProfessorEmVariosCampi = value;
    }

    /**
     * Gets the value of the minimizarDeslocProfessor property.
     * 
     */
    public boolean isMinimizarDeslocProfessor() {
        return minimizarDeslocProfessor;
    }

    /**
     * Sets the value of the minimizarDeslocProfessor property.
     * 
     */
    public void setMinimizarDeslocProfessor(boolean value) {
        this.minimizarDeslocProfessor = value;
    }

    /**
     * Gets the value of the maxDeslocProfessor property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxDeslocProfessor() {
        return maxDeslocProfessor;
    }

    /**
     * Sets the value of the maxDeslocProfessor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxDeslocProfessor(Integer value) {
        this.maxDeslocProfessor = value;
    }

    /**
     * Gets the value of the minimizarHorariosVaziosProfessor property.
     * 
     */
    public boolean isMinimizarHorariosVaziosProfessor() {
        return minimizarHorariosVaziosProfessor;
    }

    /**
     * Sets the value of the minimizarHorariosVaziosProfessor property.
     * 
     */
    public void setMinimizarHorariosVaziosProfessor(boolean value) {
        this.minimizarHorariosVaziosProfessor = value;
    }

    /**
     * Gets the value of the evitarReducaoCargaHorariaProf property.
     * 
     */
    public boolean isEvitarReducaoCargaHorariaProf() {
        return evitarReducaoCargaHorariaProf;
    }

    /**
     * Sets the value of the evitarReducaoCargaHorariaProf property.
     * 
     */
    public void setEvitarReducaoCargaHorariaProf(boolean value) {
        this.evitarReducaoCargaHorariaProf = value;
    }

    /**
     * Gets the value of the evitarReducaoCargaHorariaProfValor property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getEvitarReducaoCargaHorariaProfValor() {
        return evitarReducaoCargaHorariaProfValor;
    }

    /**
     * Sets the value of the evitarReducaoCargaHorariaProfValor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setEvitarReducaoCargaHorariaProfValor(Integer value) {
        this.evitarReducaoCargaHorariaProfValor = value;
    }

    /**
     * Gets the value of the evitarProfUltimoPrimeiroHor property.
     * 
     */
    public boolean isEvitarProfUltimoPrimeiroHor() {
        return evitarProfUltimoPrimeiroHor;
    }

    /**
     * Sets the value of the evitarProfUltimoPrimeiroHor property.
     * 
     */
    public void setEvitarProfUltimoPrimeiroHor(boolean value) {
        this.evitarProfUltimoPrimeiroHor = value;
    }
    
    /**
     * Gets the value of the evitarProfUltimoPrimeiroHorValor property.
     * 
     */
    public Integer isEvitarProfUltimoPrimeiroHorValor() {
        return evitarProfUltimoPrimeiroHorValor;
    }

    /**
     * Sets the value of the evitarProfUltimoPrimeiroHorValor property.
     * 
     */
    public void setEvitarProfUltimoPrimeiroHorValor(Integer value) {
        this.evitarProfUltimoPrimeiroHorValor = value;
    }

    /**
     * Gets the value of the preferenciaProfessorDisciplina property.
     * 
     */
    public boolean isPreferenciaProfessorDisciplina() {
        return preferenciaProfessorDisciplina;
    }

    /**
     * Sets the value of the preferenciaProfessorDisciplina property.
     * 
     */
    public void setPreferenciaProfessorDisciplina(boolean value) {
        this.preferenciaProfessorDisciplina = value;
    }

    /**
     * Gets the value of the desempenhoProfDisponibilidade property.
     * 
     */
    public boolean isDesempenhoProfDisponibilidade() {
        return desempenhoProfDisponibilidade;
    }

    /**
     * Sets the value of the desempenhoProfDisponibilidade property.
     * 
     */
    public void setDesempenhoProfDisponibilidade(boolean value) {
        this.desempenhoProfDisponibilidade = value;
    }

    /**
     * Gets the value of the funcaoObjetivo property.
     * 
     */
    public int getFuncaoObjetivo() {
        return funcaoObjetivo;
    }

    /**
     * Sets the value of the funcaoObjetivo property.
     * 
     */
    public void setFuncaoObjetivo(int value) {
        this.funcaoObjetivo = value;
    }

    /**
     * Gets the value of the considerarEquivalencia property.
     * 
     */
    public boolean isConsiderarEquivalencia() {
        return considerarEquivalencia;
    }

    /**
     * Sets the value of the considerarEquivalencia property.
     * 
     */
    public void setConsiderarEquivalencia(boolean value) {
        this.considerarEquivalencia = value;
    }

    /**
     * Gets the value of the minAlunosAberturaTurmas property.
     * 
     */
    public boolean isMinAlunosAberturaTurmas() {
        return minAlunosAberturaTurmas;
    }

    /**
     * Sets the value of the minAlunosAberturaTurmas property.
     * 
     */
    public void setMinAlunosAberturaTurmas(boolean value) {
        this.minAlunosAberturaTurmas = value;
    }

    /**
     * Gets the value of the minAlunosAberturaTurmasValor property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMinAlunosAberturaTurmasValor() {
        return minAlunosAberturaTurmasValor;
    }

    /**
     * Sets the value of the minAlunosAberturaTurmasValor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMinAlunosAberturaTurmasValor(Integer value) {
        this.minAlunosAberturaTurmasValor = value;
    }
    
    /**
     * Gets the value of the violarMinTurmasFormandos property.
     * 
     */
    public boolean isViolarMinTurmasFormandos() {
        return violarMinTurmasFormandos;
    }

    /**
     * Sets the value of the violarMinTurmasFormandos property.
     * 
     */
    public void setViolarMinTurmasFormandos(boolean value) {
        this.violarMinTurmasFormandos = value;
    }

    /**
     * Gets the value of the niveisDificuldadeHorario property.
     * 
     * @return
     *     possible object is
     *     {@link GrupoNivelDificuldadeHorario }
     *     
     */
    public GrupoNivelDificuldadeHorario getNiveisDificuldadeHorario() {
        return niveisDificuldadeHorario;
    }

    /**
     * Sets the value of the niveisDificuldadeHorario property.
     * 
     * @param value
     *     allowed object is
     *     {@link GrupoNivelDificuldadeHorario }
     *     
     */
    public void setNiveisDificuldadeHorario(GrupoNivelDificuldadeHorario value) {
        this.niveisDificuldadeHorario = value;
    }

    /**
     * Gets the value of the equilibrarDiversidadeDiscDia property.
     * 
     */
    public boolean isEquilibrarDiversidadeDiscDia() {
        return equilibrarDiversidadeDiscDia;
    }

    /**
     * Sets the value of the equilibrarDiversidadeDiscDia property.
     * 
     */
    public void setEquilibrarDiversidadeDiscDia(boolean value) {
        this.equilibrarDiversidadeDiscDia = value;
    }

    /**
     * Gets the value of the regrasGenericasDivisaoCredito property.
     * 
     */
    public boolean isRegrasGenericasDivisaoCredito() {
        return regrasGenericasDivisaoCredito;
    }

    /**
     * Sets the value of the regrasGenericasDivisaoCredito property.
     * 
     */
    public void setRegrasGenericasDivisaoCredito(boolean value) {
        this.regrasGenericasDivisaoCredito = value;
    }

    /**
     * Gets the value of the regrasEspecificasDivisaoCredito property.
     * 
     */
    public boolean isRegrasEspecificasDivisaoCredito() {
        return regrasEspecificasDivisaoCredito;
    }

    /**
     * Sets the value of the regrasEspecificasDivisaoCredito property.
     * 
     */
    public void setRegrasEspecificasDivisaoCredito(boolean value) {
        this.regrasEspecificasDivisaoCredito = value;
    }

    /**
     * Gets the value of the maximizarAvaliacaoCursosSel property.
     * 
     */
    public boolean isMaximizarAvaliacaoCursosSel() {
        return maximizarAvaliacaoCursosSel;
    }

    /**
     * Sets the value of the maximizarAvaliacaoCursosSel property.
     * 
     */
    public void setMaximizarAvaliacaoCursosSel(boolean value) {
        this.maximizarAvaliacaoCursosSel = value;
    }

    /**
     * Gets the value of the maximizarAvaliacaoCursos property.
     * 
     * @return
     *     possible object is
     *     {@link GrupoIdentificador }
     *     
     */
    public GrupoIdentificador getMaximizarAvaliacaoCursos() {
        return maximizarAvaliacaoCursos;
    }

    /**
     * Sets the value of the maximizarAvaliacaoCursos property.
     * 
     * @param value
     *     allowed object is
     *     {@link GrupoIdentificador }
     *     
     */
    public void setMaximizarAvaliacaoCursos(GrupoIdentificador value) {
        this.maximizarAvaliacaoCursos = value;
    }

    /**
     * Gets the value of the minimizarCustoDocenteCursosSel property.
     * 
     */
    public boolean isMinimizarCustoDocenteCursosSel() {
        return minimizarCustoDocenteCursosSel;
    }

    /**
     * Sets the value of the minimizarCustoDocenteCursosSel property.
     * 
     */
    public void setMinimizarCustoDocenteCursosSel(boolean value) {
        this.minimizarCustoDocenteCursosSel = value;
    }

    /**
     * Gets the value of the minimizarCustoDocenteCursos property.
     * 
     * @return
     *     possible object is
     *     {@link GrupoIdentificador }
     *     
     */
    public GrupoIdentificador getMinimizarCustoDocenteCursos() {
        return minimizarCustoDocenteCursos;
    }

    /**
     * Sets the value of the minimizarCustoDocenteCursos property.
     * 
     * @param value
     *     allowed object is
     *     {@link GrupoIdentificador }
     *     
     */
    public void setMinimizarCustoDocenteCursos(GrupoIdentificador value) {
        this.minimizarCustoDocenteCursos = value;
    }

    /**
     * Gets the value of the permiteCompartilhamentoTurmaSel property.
     * 
     */
    public boolean isPermiteCompartilhamentoTurmaSel() {
        return permiteCompartilhamentoTurmaSel;
    }

    /**
     * Sets the value of the permiteCompartilhamentoTurmaSel property.
     * 
     */
    public void setPermiteCompartilhamentoTurmaSel(boolean value) {
        this.permiteCompartilhamentoTurmaSel = value;
    }

    /**
     * Gets the value of the permiteCompartilhamentoTurma property.
     * 
     * @return
     *     possible object is
     *     {@link GrupoGrupo }
     *     
     */
    public GrupoGrupo getPermiteCompartilhamentoTurma() {
        return permiteCompartilhamentoTurma;
    }

    /**
     * Sets the value of the permiteCompartilhamentoTurma property.
     * 
     * @param value
     *     allowed object is
     *     {@link GrupoGrupo }
     *     
     */
    public void setPermiteCompartilhamentoTurma(GrupoGrupo value) {
        this.permiteCompartilhamentoTurma = value;
    }

    /**
     * Gets the value of the percentuaisMinimoMestres property.
     * 
     */
    public boolean isPercentuaisMinimoMestres() {
        return percentuaisMinimoMestres;
    }

    /**
     * Sets the value of the percentuaisMinimoMestres property.
     * 
     */
    public void setPercentuaisMinimoMestres(boolean value) {
        this.percentuaisMinimoMestres = value;
    }

    /**
     * Gets the value of the percentuaisMinimoDoutores property.
     * 
     */
    public boolean isPercentuaisMinimoDoutores() {
        return percentuaisMinimoDoutores;
    }

    /**
     * Sets the value of the percentuaisMinimoDoutores property.
     * 
     */
    public void setPercentuaisMinimoDoutores(boolean value) {
        this.percentuaisMinimoDoutores = value;
    }

    /**
     * Gets the value of the areaTitulacaoProfessorCurso property.
     * 
     */
    public boolean isAreaTitulacaoProfessorCurso() {
        return areaTitulacaoProfessorCurso;
    }

    /**
     * Sets the value of the areaTitulacaoProfessorCurso property.
     * 
     */
    public void setAreaTitulacaoProfessorCurso(boolean value) {
        this.areaTitulacaoProfessorCurso = value;
    }

    /**
     * Gets the value of the maximoDisciplinasDeUmProfessorPorCurso property.
     * 
     */
    public boolean isMaximoDisciplinasDeUmProfessorPorCurso() {
        return maximoDisciplinasDeUmProfessorPorCurso;
    }

    /**
     * Sets the value of the maximoDisciplinasDeUmProfessorPorCurso property.
     * 
     */
    public void setMaximoDisciplinasDeUmProfessorPorCurso(boolean value) {
        this.maximoDisciplinasDeUmProfessorPorCurso = value;
    }

    /**
     * Gets the value of the custoProfDisponibilidade property.
     * 
     */
    public boolean isCustoProfDisponibilidade() {
        return custoProfDisponibilidade;
    }

    /**
     * Sets the value of the custoProfDisponibilidade property.
     * 
     */
    public void setCustoProfDisponibilidade(boolean value) {
        this.custoProfDisponibilidade = value;
    }
    
    /**
     * Gets the value of the utilizarDemandasP2 property.
     * 
     */
    public boolean isUtilizarDemandasP2() {
        return utilizarDemandasP2;
    }

    /**
     * Sets the value of the utilizarDemandasP2 property.
     * 
     */
    public void setUtilizarDemandasP2(boolean value) {
        this.utilizarDemandasP2 = value;
    }
    
    /**
     * Gets the value of the percentuaisMinimoParcialIntegral property.
     * 
     */
    public boolean isPercentuaisMinimoParcialIntegral() {
        return percentuaisMinimoParcialIntegral;
    }

    /**
     * Sets the value of the percentuaisMinimoParcialIntegral property.
     * 
     */
    public void setPercentuaisMinimoParcialIntegral(boolean value) {
        this.percentuaisMinimoParcialIntegral = value;
    }
    
    /**
     * Gets the value of the percentuaisMinimoIntegral property.
     * 
     */
    public boolean isPercentuaisMinimoIntegral() {
        return percentuaisMinimoIntegral;
    }

    /**
     * Sets the value of the percentuaisMinimoIntegral property.
     * 
     */
    public void setPercentuaisMinimoIntegral(boolean value) {
        this.percentuaisMinimoIntegral = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="equilibrar" type="{http://www.w3.org/2001/XMLSchema}anySimpleType"/>
     *         &lt;element name="minimizarDias" type="{http://www.w3.org/2001/XMLSchema}anySimpleType"/>
     *         &lt;element name="indiferente" type="{http://www.w3.org/2001/XMLSchema}anySimpleType"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "equilibrar",
        "minimizarDias",
        "indiferente"
    })
    public static class CargaHorariaSemanalAluno {

        @XmlSchemaType(name = "anySimpleType")
        protected Object equilibrar;
        @XmlSchemaType(name = "anySimpleType")
        protected Object minimizarDias;
        @XmlSchemaType(name = "anySimpleType")
        protected Object indiferente;

        /**
         * Gets the value of the equilibrar property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getEquilibrar() {
            return equilibrar;
        }

        /**
         * Sets the value of the equilibrar property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setEquilibrar(Object value) {
            this.equilibrar = value;
        }

        /**
         * Gets the value of the minimizarDias property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getMinimizarDias() {
            return minimizarDias;
        }

        /**
         * Sets the value of the minimizarDias property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setMinimizarDias(Object value) {
            this.minimizarDias = value;
        }

        /**
         * Gets the value of the indiferente property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getIndiferente() {
            return indiferente;
        }

        /**
         * Sets the value of the indiferente property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setIndiferente(Object value) {
            this.indiferente = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="equilibrar" type="{http://www.w3.org/2001/XMLSchema}anySimpleType"/>
     *         &lt;element name="minimizarDias" type="{http://www.w3.org/2001/XMLSchema}anySimpleType"/>
     *         &lt;element name="indiferente" type="{http://www.w3.org/2001/XMLSchema}anySimpleType"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "equilibrar",
        "minimizarDias",
        "indiferente"
    })
    public static class CargaHorariaSemanalProfessor {

        @XmlSchemaType(name = "anySimpleType")
        protected Object equilibrar;
        @XmlSchemaType(name = "anySimpleType")
        protected Object minimizarDias;
        @XmlSchemaType(name = "anySimpleType")
        protected Object indiferente;

        /**
         * Gets the value of the equilibrar property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getEquilibrar() {
            return equilibrar;
        }

        /**
         * Sets the value of the equilibrar property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setEquilibrar(Object value) {
            this.equilibrar = value;
        }

        /**
         * Gets the value of the minimizarDias property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getMinimizarDias() {
            return minimizarDias;
        }

        /**
         * Sets the value of the minimizarDias property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setMinimizarDias(Object value) {
            this.minimizarDias = value;
        }

        /**
         * Gets the value of the indiferente property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getIndiferente() {
            return indiferente;
        }

        /**
         * Sets the value of the indiferente property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setIndiferente(Object value) {
            this.indiferente = value;
        }

    }

}
