//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.02 at 05:08:00 PM BRST 
//


package com.gapso.web.trieda.server.xml.input;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ItemProfessor complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ItemProfessor">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="cpf" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nome" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tipoContratoId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="chMin" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="chMax" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="titulacaoId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="areaTitulacaoId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="credAnterior" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="valorCred" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="horariosDisponiveis" type="{}GrupoHorario"/>
 *         &lt;element name="disciplinas" type="{}GrupoProfessorDisciplina"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ItemProfessor", propOrder = {
    "id",
    "cpf",
    "nome",
    "tipoContratoId",
    "chMin",
    "chMax",
    "titulacaoId",
    "areaTitulacaoId",
    "credAnterior",
    "valorCred",
    "horariosDisponiveis",
    "disciplinas"
})
public class ItemProfessor {

    protected int id;
    @XmlElement(required = true)
    protected String cpf;
    @XmlElement(required = true)
    protected String nome;
    protected int tipoContratoId;
    protected int chMin;
    protected int chMax;
    protected int titulacaoId;
    protected Integer areaTitulacaoId;
    protected int credAnterior;
    protected double valorCred;
    @XmlElement(required = true)
    protected GrupoHorario horariosDisponiveis;
    @XmlElement(required = true)
    protected GrupoProfessorDisciplina disciplinas;

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the cpf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCpf() {
        return cpf;
    }

    /**
     * Sets the value of the cpf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCpf(String value) {
        this.cpf = value;
    }

    /**
     * Gets the value of the nome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNome() {
        return nome;
    }

    /**
     * Sets the value of the nome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNome(String value) {
        this.nome = value;
    }

    /**
     * Gets the value of the tipoContratoId property.
     * 
     */
    public int getTipoContratoId() {
        return tipoContratoId;
    }

    /**
     * Sets the value of the tipoContratoId property.
     * 
     */
    public void setTipoContratoId(int value) {
        this.tipoContratoId = value;
    }

    /**
     * Gets the value of the chMin property.
     * 
     */
    public int getChMin() {
        return chMin;
    }

    /**
     * Sets the value of the chMin property.
     * 
     */
    public void setChMin(int value) {
        this.chMin = value;
    }

    /**
     * Gets the value of the chMax property.
     * 
     */
    public int getChMax() {
        return chMax;
    }

    /**
     * Sets the value of the chMax property.
     * 
     */
    public void setChMax(int value) {
        this.chMax = value;
    }

    /**
     * Gets the value of the titulacaoId property.
     * 
     */
    public int getTitulacaoId() {
        return titulacaoId;
    }

    /**
     * Sets the value of the titulacaoId property.
     * 
     */
    public void setTitulacaoId(int value) {
        this.titulacaoId = value;
    }

    /**
     * Gets the value of the areaTitulacaoId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAreaTitulacaoId() {
        return areaTitulacaoId;
    }

    /**
     * Sets the value of the areaTitulacaoId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAreaTitulacaoId(Integer value) {
        this.areaTitulacaoId = value;
    }

    /**
     * Gets the value of the credAnterior property.
     * 
     */
    public int getCredAnterior() {
        return credAnterior;
    }

    /**
     * Sets the value of the credAnterior property.
     * 
     */
    public void setCredAnterior(int value) {
        this.credAnterior = value;
    }

    /**
     * Gets the value of the valorCred property.
     * 
     */
    public double getValorCred() {
        return valorCred;
    }

    /**
     * Sets the value of the valorCred property.
     * 
     */
    public void setValorCred(double value) {
        this.valorCred = value;
    }

    /**
     * Gets the value of the horariosDisponiveis property.
     * 
     * @return
     *     possible object is
     *     {@link GrupoHorario }
     *     
     */
    public GrupoHorario getHorariosDisponiveis() {
        return horariosDisponiveis;
    }

    /**
     * Sets the value of the horariosDisponiveis property.
     * 
     * @param value
     *     allowed object is
     *     {@link GrupoHorario }
     *     
     */
    public void setHorariosDisponiveis(GrupoHorario value) {
        this.horariosDisponiveis = value;
    }

    /**
     * Gets the value of the disciplinas property.
     * 
     * @return
     *     possible object is
     *     {@link GrupoProfessorDisciplina }
     *     
     */
    public GrupoProfessorDisciplina getDisciplinas() {
        return disciplinas;
    }

    /**
     * Sets the value of the disciplinas property.
     * 
     * @param value
     *     allowed object is
     *     {@link GrupoProfessorDisciplina }
     *     
     */
    public void setDisciplinas(GrupoProfessorDisciplina value) {
        this.disciplinas = value;
    }

}
