//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.08 at 11:18:45 AM BRST 
//


package com.gapso.web.trieda.server.xml.input;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ItemCalendario complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ItemCalendario">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="codigo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tempoAula" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="turnos" type="{}GrupoTurno"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ItemCalendario", propOrder = {
    "id",
    "codigo",
    "tempoAula",
    "turnos"
})
public class ItemCalendario {

    protected int id;
    @XmlElement(required = true)
    protected String codigo;
    protected int tempoAula;
    @XmlElement(required = true)
    protected GrupoTurno turnos;

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the codigo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigo() {
        return codigo;
    }

    /**
     * Sets the value of the codigo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigo(String value) {
        this.codigo = value;
    }

    /**
     * Gets the value of the tempoAula property.
     * 
     */
    public int getTempoAula() {
        return tempoAula;
    }

    /**
     * Sets the value of the tempoAula property.
     * 
     */
    public void setTempoAula(int value) {
        this.tempoAula = value;
    }

    /**
     * Gets the value of the turnos property.
     * 
     * @return
     *     possible object is
     *     {@link GrupoTurno }
     *     
     */
    public GrupoTurno getTurnos() {
        return turnos;
    }

    /**
     * Sets the value of the turnos property.
     * 
     * @param value
     *     allowed object is
     *     {@link GrupoTurno }
     *     
     */
    public void setTurnos(GrupoTurno value) {
        this.turnos = value;
    }

}
