//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.08 at 11:18:45 AM BRST 
//


package com.gapso.web.trieda.server.xml.input;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.gapso.web.trieda.server.xml.input package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.gapso.web.trieda.server.xml.input
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ItemParametrosPlanejamento }
     * 
     */
    public ItemParametrosPlanejamento createItemParametrosPlanejamento() {
        return new ItemParametrosPlanejamento();
    }

    /**
     * Create an instance of {@link TriedaInput }
     * 
     */
    public TriedaInput createTriedaInput() {
        return new TriedaInput();
    }

    /**
     * Create an instance of {@link GrupoCalendario }
     * 
     */
    public GrupoCalendario createGrupoCalendario() {
        return new GrupoCalendario();
    }

    /**
     * Create an instance of {@link GrupoTipoSala }
     * 
     */
    public GrupoTipoSala createGrupoTipoSala() {
        return new GrupoTipoSala();
    }

    /**
     * Create an instance of {@link GrupoTipoContrato }
     * 
     */
    public GrupoTipoContrato createGrupoTipoContrato() {
        return new GrupoTipoContrato();
    }

    /**
     * Create an instance of {@link GrupoTipoTitulacao }
     * 
     */
    public GrupoTipoTitulacao createGrupoTipoTitulacao() {
        return new GrupoTipoTitulacao();
    }

    /**
     * Create an instance of {@link GrupoAreaTitulacao }
     * 
     */
    public GrupoAreaTitulacao createGrupoAreaTitulacao() {
        return new GrupoAreaTitulacao();
    }

    /**
     * Create an instance of {@link GrupoTipoDisciplina }
     * 
     */
    public GrupoTipoDisciplina createGrupoTipoDisciplina() {
        return new GrupoTipoDisciplina();
    }

    /**
     * Create an instance of {@link GrupoNivelDificuldade }
     * 
     */
    public GrupoNivelDificuldade createGrupoNivelDificuldade() {
        return new GrupoNivelDificuldade();
    }

    /**
     * Create an instance of {@link GrupoTipoCurso }
     * 
     */
    public GrupoTipoCurso createGrupoTipoCurso() {
        return new GrupoTipoCurso();
    }

    /**
     * Create an instance of {@link GrupoDivisaoCreditos }
     * 
     */
    public GrupoDivisaoCreditos createGrupoDivisaoCreditos() {
        return new GrupoDivisaoCreditos();
    }

    /**
     * Create an instance of {@link GrupoCampus }
     * 
     */
    public GrupoCampus createGrupoCampus() {
        return new GrupoCampus();
    }

    /**
     * Create an instance of {@link GrupoDeslocamento }
     * 
     */
    public GrupoDeslocamento createGrupoDeslocamento() {
        return new GrupoDeslocamento();
    }

    /**
     * Create an instance of {@link GrupoDisciplina }
     * 
     */
    public GrupoDisciplina createGrupoDisciplina() {
        return new GrupoDisciplina();
    }

    /**
     * Create an instance of {@link GrupoCurso }
     * 
     */
    public GrupoCurso createGrupoCurso() {
        return new GrupoCurso();
    }

    /**
     * Create an instance of {@link GrupoOfertaCurso }
     * 
     */
    public GrupoOfertaCurso createGrupoOfertaCurso() {
        return new GrupoOfertaCurso();
    }

    /**
     * Create an instance of {@link GrupoDemanda }
     * 
     */
    public GrupoDemanda createGrupoDemanda() {
        return new GrupoDemanda();
    }

    /**
     * Create an instance of {@link GrupoAlunoDemanda }
     * 
     */
    public GrupoAlunoDemanda createGrupoAlunoDemanda() {
        return new GrupoAlunoDemanda();
    }
    
    /**
     * Create an instance of {@link GrupoAlunos }
     * 
     */
    public GrupoAlunos createGrupoAlunos() {
        return new GrupoAlunos();
    }

    /**
     * Create an instance of {@link GrupoFixacao }
     * 
     */
    public GrupoFixacao createGrupoFixacao() {
        return new GrupoFixacao();
    }

    /**
     * Create an instance of {@link GrupoAtendimentoCampusSolucao }
     * 
     */
    public GrupoAtendimentoCampusSolucao createGrupoAtendimentoCampusSolucao() {
        return new GrupoAtendimentoCampusSolucao();
    }

    /**
     * Create an instance of {@link GrupoAtendimentoUnidadeSolucao }
     * 
     */
    public GrupoAtendimentoUnidadeSolucao createGrupoAtendimentoUnidadeSolucao() {
        return new GrupoAtendimentoUnidadeSolucao();
    }

    /**
     * Create an instance of {@link ItemTipoTitulacao }
     * 
     */
    public ItemTipoTitulacao createItemTipoTitulacao() {
        return new ItemTipoTitulacao();
    }

    /**
     * Create an instance of {@link ItemCalendario }
     * 
     */
    public ItemCalendario createItemCalendario() {
        return new ItemCalendario();
    }

    /**
     * Create an instance of {@link ItemNivelDificuldade }
     * 
     */
    public ItemNivelDificuldade createItemNivelDificuldade() {
        return new ItemNivelDificuldade();
    }

    /**
     * Create an instance of {@link ItemTipoDisciplina }
     * 
     */
    public ItemTipoDisciplina createItemTipoDisciplina() {
        return new ItemTipoDisciplina();
    }

    /**
     * Create an instance of {@link ItemDisciplinaPeriodo }
     * 
     */
    public ItemDisciplinaPeriodo createItemDisciplinaPeriodo() {
        return new ItemDisciplinaPeriodo();
    }

    /**
     * Create an instance of {@link GrupoNivelDificuldadeHorario }
     * 
     */
    public GrupoNivelDificuldadeHorario createGrupoNivelDificuldadeHorario() {
        return new GrupoNivelDificuldadeHorario();
    }

    /**
     * Create an instance of {@link ItemAtendimentoOfertaSolucao }
     * 
     */
    public ItemAtendimentoOfertaSolucao createItemAtendimentoOfertaSolucao() {
        return new ItemAtendimentoOfertaSolucao();
    }

    /**
     * Create an instance of {@link ItemDemanda }
     * 
     */
    public ItemDemanda createItemDemanda() {
        return new ItemDemanda();
    }

    /**
     * Create an instance of {@link ItemFixacao }
     * 
     */
    public ItemFixacao createItemFixacao() {
        return new ItemFixacao();
    }

    /**
     * Create an instance of {@link GrupoAtendimentoTaticoSolucao }
     * 
     */
    public GrupoAtendimentoTaticoSolucao createGrupoAtendimentoTaticoSolucao() {
        return new GrupoAtendimentoTaticoSolucao();
    }

    /**
     * Create an instance of {@link ItemCreditoDisponivel }
     * 
     */
    public ItemCreditoDisponivel createItemCreditoDisponivel() {
        return new ItemCreditoDisponivel();
    }

    /**
     * Create an instance of {@link GrupoDiaSemana }
     * 
     */
    public GrupoDiaSemana createGrupoDiaSemana() {
        return new GrupoDiaSemana();
    }

    /**
     * Create an instance of {@link ItemTurno }
     * 
     */
    public ItemTurno createItemTurno() {
        return new ItemTurno();
    }

    /**
     * Create an instance of {@link ItemProfessor }
     * 
     */
    public ItemProfessor createItemProfessor() {
        return new ItemProfessor();
    }

    /**
     * Create an instance of {@link ItemSala }
     * 
     */
    public ItemSala createItemSala() {
        return new ItemSala();
    }

    /**
     * Create an instance of {@link ItemUnidade }
     * 
     */
    public ItemUnidade createItemUnidade() {
        return new ItemUnidade();
    }

    /**
     * Create an instance of {@link GrupoHorarioAula }
     * 
     */
    public GrupoHorarioAula createGrupoHorarioAula() {
        return new GrupoHorarioAula();
    }

    /**
     * Create an instance of {@link ItemNivelDificuldadeHorario }
     * 
     */
    public ItemNivelDificuldadeHorario createItemNivelDificuldadeHorario() {
        return new ItemNivelDificuldadeHorario();
    }

    /**
     * Create an instance of {@link ItemDeslocamento }
     * 
     */
    public ItemDeslocamento createItemDeslocamento() {
        return new ItemDeslocamento();
    }

    /**
     * Create an instance of {@link ItemHorarioAula }
     * 
     */
    public ItemHorarioAula createItemHorarioAula() {
        return new ItemHorarioAula();
    }

    /**
     * Create an instance of {@link GrupoIdentificador }
     * 
     */
    public GrupoIdentificador createGrupoIdentificador() {
        return new GrupoIdentificador();
    }

    /**
     * Create an instance of {@link ItemOfertaCurso }
     * 
     */
    public ItemOfertaCurso createItemOfertaCurso() {
        return new ItemOfertaCurso();
    }

    /**
     * Create an instance of {@link GrupoAtendimentoDiaSemanaSolucao }
     * 
     */
    public GrupoAtendimentoDiaSemanaSolucao createGrupoAtendimentoDiaSemanaSolucao() {
        return new GrupoAtendimentoDiaSemanaSolucao();
    }

    /**
     * Create an instance of {@link ItemAtendimentoCampusSolucao }
     * 
     */
    public ItemAtendimentoCampusSolucao createItemAtendimentoCampusSolucao() {
        return new ItemAtendimentoCampusSolucao();
    }

    /**
     * Create an instance of {@link ItemTipoCurso }
     * 
     */
    public ItemTipoCurso createItemTipoCurso() {
        return new ItemTipoCurso();
    }

    /**
     * Create an instance of {@link GrupoAtendimentoSalaSolucao }
     * 
     */
    public GrupoAtendimentoSalaSolucao createGrupoAtendimentoSalaSolucao() {
        return new GrupoAtendimentoSalaSolucao();
    }

    /**
     * Create an instance of {@link ItemDivisaoCreditos }
     * 
     */
    public ItemDivisaoCreditos createItemDivisaoCreditos() {
        return new ItemDivisaoCreditos();
    }

    /**
     * Create an instance of {@link ItemPercentualMinimo }
     * 
     */
    public ItemPercentualMinimo createItemPercentualMinimo() {
        return new ItemPercentualMinimo();
    }

    /**
     * Create an instance of {@link GrupoUnidade }
     * 
     */
    public GrupoUnidade createGrupoUnidade() {
        return new GrupoUnidade();
    }

    /**
     * Create an instance of {@link GrupoCurriculo }
     * 
     */
    public GrupoCurriculo createGrupoCurriculo() {
        return new GrupoCurriculo();
    }

    /**
     * Create an instance of {@link ItemCampus }
     * 
     */
    public ItemCampus createItemCampus() {
        return new ItemCampus();
    }

    /**
     * Create an instance of {@link ItemHorario }
     * 
     */
    public ItemHorario createItemHorario() {
        return new ItemHorario();
    }

    /**
     * Create an instance of {@link ItemCurriculo }
     * 
     */
    public ItemCurriculo createItemCurriculo() {
        return new ItemCurriculo();
    }

    /**
     * Create an instance of {@link ItemTipoSala }
     * 
     */
    public ItemTipoSala createItemTipoSala() {
        return new ItemTipoSala();
    }

    /**
     * Create an instance of {@link GrupoCreditoDisponivel }
     * 
     */
    public GrupoCreditoDisponivel createGrupoCreditoDisponivel() {
        return new GrupoCreditoDisponivel();
    }

    /**
     * Create an instance of {@link GrupoHorario }
     * 
     */
    public GrupoHorario createGrupoHorario() {
        return new GrupoHorario();
    }

    /**
     * Create an instance of {@link GrupoDisciplinaPeriodo }
     * 
     */
    public GrupoDisciplinaPeriodo createGrupoDisciplinaPeriodo() {
        return new GrupoDisciplinaPeriodo();
    }

    /**
     * Create an instance of {@link GrupoProfessor }
     * 
     */
    public GrupoProfessor createGrupoProfessor() {
        return new GrupoProfessor();
    }

    /**
     * Create an instance of {@link GrupoSala }
     * 
     */
    public GrupoSala createGrupoSala() {
        return new GrupoSala();
    }

    /**
     * Create an instance of {@link GrupoProfessorDisciplina }
     * 
     */
    public GrupoProfessorDisciplina createGrupoProfessorDisciplina() {
        return new GrupoProfessorDisciplina();
    }

    /**
     * Create an instance of {@link ItemAtendimentoTaticoSolucao }
     * 
     */
    public ItemAtendimentoTaticoSolucao createItemAtendimentoTaticoSolucao() {
        return new ItemAtendimentoTaticoSolucao();
    }

    /**
     * Create an instance of {@link ItemAtendimentoUnidadeSolucao }
     * 
     */
    public ItemAtendimentoUnidadeSolucao createItemAtendimentoUnidadeSolucao() {
        return new ItemAtendimentoUnidadeSolucao();
    }

    /**
     * Create an instance of {@link ItemProfessorDisciplina }
     * 
     */
    public ItemProfessorDisciplina createItemProfessorDisciplina() {
        return new ItemProfessorDisciplina();
    }

    /**
     * Create an instance of {@link ItemCurso }
     * 
     */
    public ItemCurso createItemCurso() {
        return new ItemCurso();
    }

    /**
     * Create an instance of {@link ItemAreaTitulacao }
     * 
     */
    public ItemAreaTitulacao createItemAreaTitulacao() {
        return new ItemAreaTitulacao();
    }

    /**
     * Create an instance of {@link ItemDisciplina }
     * 
     */
    public ItemDisciplina createItemDisciplina() {
        return new ItemDisciplina();
    }

    /**
     * Create an instance of {@link GrupoGrupo }
     * 
     */
    public GrupoGrupo createGrupoGrupo() {
        return new GrupoGrupo();
    }

    /**
     * Create an instance of {@link ItemTipoContrato }
     * 
     */
    public ItemTipoContrato createItemTipoContrato() {
        return new ItemTipoContrato();
    }

    /**
     * Create an instance of {@link GrupoTurno }
     * 
     */
    public GrupoTurno createGrupoTurno() {
        return new GrupoTurno();
    }

    /**
     * Create an instance of {@link ItemAtendimentoDiaSemanaSolucao }
     * 
     */
    public ItemAtendimentoDiaSemanaSolucao createItemAtendimentoDiaSemanaSolucao() {
        return new ItemAtendimentoDiaSemanaSolucao();
    }
    
    /**
     * Create an instance of {@link ItemAluno }
     * 
     */
    public ItemAluno createItemAluno() {
        return new ItemAluno();
    }

    /**
     * Create an instance of {@link ItemAlunoDemanda }
     * 
     */
    public ItemAlunoDemanda createItemAlunoDemanda() {
        return new ItemAlunoDemanda();
    }

    /**
     * Create an instance of {@link ItemAtendimentoSalaSolucao }
     * 
     */
    public ItemAtendimentoSalaSolucao createItemAtendimentoSalaSolucao() {
        return new ItemAtendimentoSalaSolucao();
    }

    /**
     * Create an instance of {@link ItemParametrosPlanejamento.CargaHorariaSemanalAluno }
     * 
     */
    public ItemParametrosPlanejamento.CargaHorariaSemanalAluno createItemParametrosPlanejamentoCargaHorariaSemanalAluno() {
        return new ItemParametrosPlanejamento.CargaHorariaSemanalAluno();
    }

    /**
     * Create an instance of {@link ItemParametrosPlanejamento.CargaHorariaSemanalProfessor }
     * 
     */
    public ItemParametrosPlanejamento.CargaHorariaSemanalProfessor createItemParametrosPlanejamentoCargaHorariaSemanalProfessor() {
        return new ItemParametrosPlanejamento.CargaHorariaSemanalProfessor();
    }

}
