//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.12 at 01:06:23 PM BRST 
//


package com.gapso.web.trieda.server.xml.input;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.gapso.web.trieda.server.xml.input package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.gapso.web.trieda.server.xml.input
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ItemDivisaoCreditos }
     * 
     */
    public ItemDivisaoCreditos createItemDivisaoCreditos() {
        return new ItemDivisaoCreditos();
    }

    /**
     * Create an instance of {@link ItemTipoTitulacao }
     * 
     */
    public ItemTipoTitulacao createItemTipoTitulacao() {
        return new ItemTipoTitulacao();
    }

    /**
     * Create an instance of {@link ItemAtendimentoCampus }
     * 
     */
    public ItemAtendimentoCampus createItemAtendimentoCampus() {
        return new ItemAtendimentoCampus();
    }

    /**
     * Create an instance of {@link GrupoTipoTitulacao }
     * 
     */
    public GrupoTipoTitulacao createGrupoTipoTitulacao() {
        return new GrupoTipoTitulacao();
    }

    /**
     * Create an instance of {@link GrupoFixacao }
     * 
     */
    public GrupoFixacao createGrupoFixacao() {
        return new GrupoFixacao();
    }

    /**
     * Create an instance of {@link ItemAtendimentoTatico }
     * 
     */
    public ItemAtendimentoTatico createItemAtendimentoTatico() {
        return new ItemAtendimentoTatico();
    }

    /**
     * Create an instance of {@link GrupoCurso }
     * 
     */
    public GrupoCurso createGrupoCurso() {
        return new GrupoCurso();
    }

    /**
     * Create an instance of {@link ItemOfertaCurso }
     * 
     */
    public ItemOfertaCurso createItemOfertaCurso() {
        return new ItemOfertaCurso();
    }

    /**
     * Create an instance of {@link ItemAtendimentoUnidade }
     * 
     */
    public ItemAtendimentoUnidade createItemAtendimentoUnidade() {
        return new ItemAtendimentoUnidade();
    }

    /**
     * Create an instance of {@link ItemAtendimentoSala }
     * 
     */
    public ItemAtendimentoSala createItemAtendimentoSala() {
        return new ItemAtendimentoSala();
    }

    /**
     * Create an instance of {@link GrupoCurriculo }
     * 
     */
    public GrupoCurriculo createGrupoCurriculo() {
        return new GrupoCurriculo();
    }

    /**
     * Create an instance of {@link ItemTipoContrato }
     * 
     */
    public ItemTipoContrato createItemTipoContrato() {
        return new ItemTipoContrato();
    }

    /**
     * Create an instance of {@link GrupoAtendimentoOferta }
     * 
     */
    public GrupoAtendimentoOferta createGrupoAtendimentoOferta() {
        return new GrupoAtendimentoOferta();
    }

    /**
     * Create an instance of {@link ItemError }
     * 
     */
    public ItemError createItemError() {
        return new ItemError();
    }

    /**
     * Create an instance of {@link GrupoWarning }
     * 
     */
    public GrupoWarning createGrupoWarning() {
        return new GrupoWarning();
    }

    /**
     * Create an instance of {@link ItemAtendimentoHorarioAula }
     * 
     */
    public ItemAtendimentoHorarioAula createItemAtendimentoHorarioAula() {
        return new ItemAtendimentoHorarioAula();
    }

    /**
     * Create an instance of {@link ItemCreditoDisponivel }
     * 
     */
    public ItemCreditoDisponivel createItemCreditoDisponivel() {
        return new ItemCreditoDisponivel();
    }

    /**
     * Create an instance of {@link ItemTurno }
     * 
     */
    public ItemTurno createItemTurno() {
        return new ItemTurno();
    }

    /**
     * Create an instance of {@link GrupoSala }
     * 
     */
    public GrupoSala createGrupoSala() {
        return new GrupoSala();
    }

    /**
     * Create an instance of {@link ItemAreaTitulacao }
     * 
     */
    public ItemAreaTitulacao createItemAreaTitulacao() {
        return new ItemAreaTitulacao();
    }

    /**
     * Create an instance of {@link ItemAtendimentoDiaSemana }
     * 
     */
    public ItemAtendimentoDiaSemana createItemAtendimentoDiaSemana() {
        return new ItemAtendimentoDiaSemana();
    }

    /**
     * Create an instance of {@link ItemDisciplina }
     * 
     */
    public ItemDisciplina createItemDisciplina() {
        return new ItemDisciplina();
    }

    /**
     * Create an instance of {@link TriedaOutput }
     * 
     */
    public TriedaOutput createTriedaOutput() {
        return new TriedaOutput();
    }

    /**
     * Create an instance of {@link GrupoUnidade }
     * 
     */
    public GrupoUnidade createGrupoUnidade() {
        return new GrupoUnidade();
    }

    /**
     * Create an instance of {@link GrupoError }
     * 
     */
    public GrupoError createGrupoError() {
        return new GrupoError();
    }

    /**
     * Create an instance of {@link GrupoNivelDificuldade }
     * 
     */
    public GrupoNivelDificuldade createGrupoNivelDificuldade() {
        return new GrupoNivelDificuldade();
    }

    /**
     * Create an instance of {@link ItemCurriculo }
     * 
     */
    public ItemCurriculo createItemCurriculo() {
        return new ItemCurriculo();
    }

    /**
     * Create an instance of {@link GrupoAtendimentoTatico }
     * 
     */
    public GrupoAtendimentoTatico createGrupoAtendimentoTatico() {
        return new GrupoAtendimentoTatico();
    }

    /**
     * Create an instance of {@link GrupoAtendimentoUnidade }
     * 
     */
    public GrupoAtendimentoUnidade createGrupoAtendimentoUnidade() {
        return new GrupoAtendimentoUnidade();
    }

    /**
     * Create an instance of {@link ItemParametrosPlanejamento }
     * 
     */
    public ItemParametrosPlanejamento createItemParametrosPlanejamento() {
        return new ItemParametrosPlanejamento();
    }

    /**
     * Create an instance of {@link GrupoProfessorDisciplina }
     * 
     */
    public GrupoProfessorDisciplina createGrupoProfessorDisciplina() {
        return new GrupoProfessorDisciplina();
    }

    /**
     * Create an instance of {@link GrupoProfessor }
     * 
     */
    public GrupoProfessor createGrupoProfessor() {
        return new GrupoProfessor();
    }

    /**
     * Create an instance of {@link GrupoOfertaCurso }
     * 
     */
    public GrupoOfertaCurso createGrupoOfertaCurso() {
        return new GrupoOfertaCurso();
    }

    /**
     * Create an instance of {@link ItemParametrosPlanejamento.CargaHorariaSemanalAluno }
     * 
     */
    public ItemParametrosPlanejamento.CargaHorariaSemanalAluno createItemParametrosPlanejamentoCargaHorariaSemanalAluno() {
        return new ItemParametrosPlanejamento.CargaHorariaSemanalAluno();
    }

    /**
     * Create an instance of {@link GrupoTipoSala }
     * 
     */
    public GrupoTipoSala createGrupoTipoSala() {
        return new GrupoTipoSala();
    }

    /**
     * Create an instance of {@link ItemHorario }
     * 
     */
    public ItemHorario createItemHorario() {
        return new ItemHorario();
    }

    /**
     * Create an instance of {@link GrupoAreaTitulacao }
     * 
     */
    public GrupoAreaTitulacao createGrupoAreaTitulacao() {
        return new GrupoAreaTitulacao();
    }

    /**
     * Create an instance of {@link GrupoTurno }
     * 
     */
    public GrupoTurno createGrupoTurno() {
        return new GrupoTurno();
    }

    /**
     * Create an instance of {@link GrupoAtendimentoTurno }
     * 
     */
    public GrupoAtendimentoTurno createGrupoAtendimentoTurno() {
        return new GrupoAtendimentoTurno();
    }

    /**
     * Create an instance of {@link GrupoHorario }
     * 
     */
    public GrupoHorario createGrupoHorario() {
        return new GrupoHorario();
    }

    /**
     * Create an instance of {@link GrupoDisciplina }
     * 
     */
    public GrupoDisciplina createGrupoDisciplina() {
        return new GrupoDisciplina();
    }

    /**
     * Create an instance of {@link GrupoAtendimentoCampus }
     * 
     */
    public GrupoAtendimentoCampus createGrupoAtendimentoCampus() {
        return new GrupoAtendimentoCampus();
    }

    /**
     * Create an instance of {@link GrupoDemanda }
     * 
     */
    public GrupoDemanda createGrupoDemanda() {
        return new GrupoDemanda();
    }

    /**
     * Create an instance of {@link ItemTipoDisciplina }
     * 
     */
    public ItemTipoDisciplina createItemTipoDisciplina() {
        return new ItemTipoDisciplina();
    }

    /**
     * Create an instance of {@link GrupoHorarioAula }
     * 
     */
    public GrupoHorarioAula createGrupoHorarioAula() {
        return new GrupoHorarioAula();
    }

    /**
     * Create an instance of {@link GrupoDivisaoCreditos }
     * 
     */
    public GrupoDivisaoCreditos createGrupoDivisaoCreditos() {
        return new GrupoDivisaoCreditos();
    }

    /**
     * Create an instance of {@link ItemOperacional }
     * 
     */
    public ItemOperacional createItemOperacional() {
        return new ItemOperacional();
    }

    /**
     * Create an instance of {@link ItemTipoCurso }
     * 
     */
    public ItemTipoCurso createItemTipoCurso() {
        return new ItemTipoCurso();
    }

    /**
     * Create an instance of {@link ItemProfessor }
     * 
     */
    public ItemProfessor createItemProfessor() {
        return new ItemProfessor();
    }

    /**
     * Create an instance of {@link TriedaInput }
     * 
     */
    public TriedaInput createTriedaInput() {
        return new TriedaInput();
    }

    /**
     * Create an instance of {@link ItemCurso }
     * 
     */
    public ItemCurso createItemCurso() {
        return new ItemCurso();
    }

    /**
     * Create an instance of {@link ItemAtendimentoTurno }
     * 
     */
    public ItemAtendimentoTurno createItemAtendimentoTurno() {
        return new ItemAtendimentoTurno();
    }

    /**
     * Create an instance of {@link ItemDemanda }
     * 
     */
    public ItemDemanda createItemDemanda() {
        return new ItemDemanda();
    }

    /**
     * Create an instance of {@link GrupoDiaSemana }
     * 
     */
    public GrupoDiaSemana createGrupoDiaSemana() {
        return new GrupoDiaSemana();
    }

    /**
     * Create an instance of {@link ItemNivelDificuldade }
     * 
     */
    public ItemNivelDificuldade createItemNivelDificuldade() {
        return new ItemNivelDificuldade();
    }

    /**
     * Create an instance of {@link GrupoCampus }
     * 
     */
    public GrupoCampus createGrupoCampus() {
        return new GrupoCampus();
    }

    /**
     * Create an instance of {@link ItemTipoSala }
     * 
     */
    public ItemTipoSala createItemTipoSala() {
        return new ItemTipoSala();
    }

    /**
     * Create an instance of {@link ItemSala }
     * 
     */
    public ItemSala createItemSala() {
        return new ItemSala();
    }

    /**
     * Create an instance of {@link ItemUnidade }
     * 
     */
    public ItemUnidade createItemUnidade() {
        return new ItemUnidade();
    }

    /**
     * Create an instance of {@link GrupoAtendimentoDiaSemana }
     * 
     */
    public GrupoAtendimentoDiaSemana createGrupoAtendimentoDiaSemana() {
        return new GrupoAtendimentoDiaSemana();
    }

    /**
     * Create an instance of {@link GrupoIdentificador }
     * 
     */
    public GrupoIdentificador createGrupoIdentificador() {
        return new GrupoIdentificador();
    }

    /**
     * Create an instance of {@link ItemPercentualMinimo }
     * 
     */
    public ItemPercentualMinimo createItemPercentualMinimo() {
        return new ItemPercentualMinimo();
    }

    /**
     * Create an instance of {@link GrupoNivelDificuldadeHorario }
     * 
     */
    public GrupoNivelDificuldadeHorario createGrupoNivelDificuldadeHorario() {
        return new GrupoNivelDificuldadeHorario();
    }

    /**
     * Create an instance of {@link GrupoAtendimentoSala }
     * 
     */
    public GrupoAtendimentoSala createGrupoAtendimentoSala() {
        return new GrupoAtendimentoSala();
    }

    /**
     * Create an instance of {@link GrupoDisciplinaPeriodo }
     * 
     */
    public GrupoDisciplinaPeriodo createGrupoDisciplinaPeriodo() {
        return new GrupoDisciplinaPeriodo();
    }

    /**
     * Create an instance of {@link ItemFixacao }
     * 
     */
    public ItemFixacao createItemFixacao() {
        return new ItemFixacao();
    }

    /**
     * Create an instance of {@link GrupoTipoDisciplina }
     * 
     */
    public GrupoTipoDisciplina createGrupoTipoDisciplina() {
        return new GrupoTipoDisciplina();
    }

    /**
     * Create an instance of {@link ItemCalendario }
     * 
     */
    public ItemCalendario createItemCalendario() {
        return new ItemCalendario();
    }

    /**
     * Create an instance of {@link ItemDisciplinaPeriodo }
     * 
     */
    public ItemDisciplinaPeriodo createItemDisciplinaPeriodo() {
        return new ItemDisciplinaPeriodo();
    }

    /**
     * Create an instance of {@link ItemWarning }
     * 
     */
    public ItemWarning createItemWarning() {
        return new ItemWarning();
    }

    /**
     * Create an instance of {@link ItemHorarioAula }
     * 
     */
    public ItemHorarioAula createItemHorarioAula() {
        return new ItemHorarioAula();
    }

    /**
     * Create an instance of {@link GrupoTipoCurso }
     * 
     */
    public GrupoTipoCurso createGrupoTipoCurso() {
        return new GrupoTipoCurso();
    }

    /**
     * Create an instance of {@link ItemDeslocamento }
     * 
     */
    public ItemDeslocamento createItemDeslocamento() {
        return new ItemDeslocamento();
    }

    /**
     * Create an instance of {@link GrupoCreditoDisponivel }
     * 
     */
    public GrupoCreditoDisponivel createGrupoCreditoDisponivel() {
        return new GrupoCreditoDisponivel();
    }

    /**
     * Create an instance of {@link GrupoGrupo }
     * 
     */
    public GrupoGrupo createGrupoGrupo() {
        return new GrupoGrupo();
    }

    /**
     * Create an instance of {@link GrupoDeslocamento }
     * 
     */
    public GrupoDeslocamento createGrupoDeslocamento() {
        return new GrupoDeslocamento();
    }

    /**
     * Create an instance of {@link ItemAtendimentoOferta }
     * 
     */
    public ItemAtendimentoOferta createItemAtendimentoOferta() {
        return new ItemAtendimentoOferta();
    }

    /**
     * Create an instance of {@link ItemNivelDificuldadeHorario }
     * 
     */
    public ItemNivelDificuldadeHorario createItemNivelDificuldadeHorario() {
        return new ItemNivelDificuldadeHorario();
    }

    /**
     * Create an instance of {@link GrupoAtendimentoHorarioAula }
     * 
     */
    public GrupoAtendimentoHorarioAula createGrupoAtendimentoHorarioAula() {
        return new GrupoAtendimentoHorarioAula();
    }

    /**
     * Create an instance of {@link GrupoTipoContrato }
     * 
     */
    public GrupoTipoContrato createGrupoTipoContrato() {
        return new GrupoTipoContrato();
    }

    /**
     * Create an instance of {@link ItemCampus }
     * 
     */
    public ItemCampus createItemCampus() {
        return new ItemCampus();
    }

    /**
     * Create an instance of {@link ItemProfessorDisciplina }
     * 
     */
    public ItemProfessorDisciplina createItemProfessorDisciplina() {
        return new ItemProfessorDisciplina();
    }

}
