//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.27 at 09:12:24 AM BRT 
//


package com.gapso.web.trieda.server.xml.output;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ItemProfessorVirtual complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ItemProfessorVirtual">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="chMin" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="chMax" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="titulacaoId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="areaTitulacaoId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="disciplinas" type="{}GrupoIdentificador"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ItemProfessorVirtual", propOrder = {
    "id",
    "chMin",
    "chMax",
    "titulacaoId",
    "areaTitulacaoId",
    "disciplinas"
})
public class ItemProfessorVirtual {

    protected int id;
    protected int chMin;
    protected int chMax;
    protected int titulacaoId;
    protected Integer areaTitulacaoId;
    @XmlElement(required = true)
    protected GrupoIdentificador disciplinas;

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the chMin property.
     * 
     */
    public int getChMin() {
        return chMin;
    }

    /**
     * Sets the value of the chMin property.
     * 
     */
    public void setChMin(int value) {
        this.chMin = value;
    }

    /**
     * Gets the value of the chMax property.
     * 
     */
    public int getChMax() {
        return chMax;
    }

    /**
     * Sets the value of the chMax property.
     * 
     */
    public void setChMax(int value) {
        this.chMax = value;
    }

    /**
     * Gets the value of the titulacaoId property.
     * 
     */
    public int getTitulacaoId() {
        return titulacaoId;
    }

    /**
     * Sets the value of the titulacaoId property.
     * 
     */
    public void setTitulacaoId(int value) {
        this.titulacaoId = value;
    }

    /**
     * Gets the value of the areaTitulacaoId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAreaTitulacaoId() {
        return areaTitulacaoId;
    }

    /**
     * Sets the value of the areaTitulacaoId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAreaTitulacaoId(Integer value) {
        this.areaTitulacaoId = value;
    }

    /**
     * Gets the value of the disciplinas property.
     * 
     * @return
     *     possible object is
     *     {@link GrupoIdentificador }
     *     
     */
    public GrupoIdentificador getDisciplinas() {
        return disciplinas;
    }

    /**
     * Sets the value of the disciplinas property.
     * 
     * @param value
     *     allowed object is
     *     {@link GrupoIdentificador }
     *     
     */
    public void setDisciplinas(GrupoIdentificador value) {
        this.disciplinas = value;
    }

}
