//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.23 at 05:21:16 PM BRT 
//


package com.gapso.web.trieda.server.xml.output;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.gapso.web.trieda.server.xml.output package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.gapso.web.trieda.server.xml.output
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TriedaOutput }
     * 
     */
    public TriedaOutput createTriedaOutput() {
        return new TriedaOutput();
    }

    /**
     * Create an instance of {@link TriedaOutput.RestricoesVioladas }
     * 
     */
    public TriedaOutput.RestricoesVioladas createTriedaOutputRestricoesVioladas() {
        return new TriedaOutput.RestricoesVioladas();
    }

    /**
     * Create an instance of {@link GrupoAtendimentoCampus }
     * 
     */
    public GrupoAtendimentoCampus createGrupoAtendimentoCampus() {
        return new GrupoAtendimentoCampus();
    }

    /**
     * Create an instance of {@link GrupoWarning }
     * 
     */
    public GrupoWarning createGrupoWarning() {
        return new GrupoWarning();
    }

    /**
     * Create an instance of {@link GrupoError }
     * 
     */
    public GrupoError createGrupoError() {
        return new GrupoError();
    }

    /**
     * Create an instance of {@link GrupoProfessoresVirtuais }
     * 
     */
    public GrupoProfessoresVirtuais createGrupoProfessoresVirtuais() {
        return new GrupoProfessoresVirtuais();
    }

    /**
     * Create an instance of {@link GrupoAlunoDemanda }
     * 
     */
    public GrupoAlunoDemanda createGrupoAlunoDemanda() {
        return new GrupoAlunoDemanda();
    }

    /**
     * Create an instance of {@link ItemWarning }
     * 
     */
    public ItemWarning createItemWarning() {
        return new ItemWarning();
    }

    /**
     * Create an instance of {@link ItemAtendimentoTatico }
     * 
     */
    public ItemAtendimentoTatico createItemAtendimentoTatico() {
        return new ItemAtendimentoTatico();
    }

    /**
     * Create an instance of {@link ItemOperacional }
     * 
     */
    public ItemOperacional createItemOperacional() {
        return new ItemOperacional();
    }

    /**
     * Create an instance of {@link ItemProfessorVirtual }
     * 
     */
    public ItemProfessorVirtual createItemProfessorVirtual() {
        return new ItemProfessorVirtual();
    }

    /**
     * Create an instance of {@link ItemAtendimentoTurno }
     * 
     */
    public ItemAtendimentoTurno createItemAtendimentoTurno() {
        return new ItemAtendimentoTurno();
    }

    /**
     * Create an instance of {@link ItemAtendimentoCampus }
     * 
     */
    public ItemAtendimentoCampus createItemAtendimentoCampus() {
        return new ItemAtendimentoCampus();
    }

    /**
     * Create an instance of {@link ItemAtendimentoUnidade }
     * 
     */
    public ItemAtendimentoUnidade createItemAtendimentoUnidade() {
        return new ItemAtendimentoUnidade();
    }

    /**
     * Create an instance of {@link GrupoAtendimentoTurno }
     * 
     */
    public GrupoAtendimentoTurno createGrupoAtendimentoTurno() {
        return new GrupoAtendimentoTurno();
    }

    /**
     * Create an instance of {@link GrupoAtendimentoHorarioAula }
     * 
     */
    public GrupoAtendimentoHorarioAula createGrupoAtendimentoHorarioAula() {
        return new GrupoAtendimentoHorarioAula();
    }

    /**
     * Create an instance of {@link ItemAtendimentoOferta }
     * 
     */
    public ItemAtendimentoOferta createItemAtendimentoOferta() {
        return new ItemAtendimentoOferta();
    }

    /**
     * Create an instance of {@link ItemAtendimentoSala }
     * 
     */
    public ItemAtendimentoSala createItemAtendimentoSala() {
        return new ItemAtendimentoSala();
    }

    /**
     * Create an instance of {@link ItemError }
     * 
     */
    public ItemError createItemError() {
        return new ItemError();
    }

    /**
     * Create an instance of {@link ItemAtendimentoDiaSemana }
     * 
     */
    public ItemAtendimentoDiaSemana createItemAtendimentoDiaSemana() {
        return new ItemAtendimentoDiaSemana();
    }

    /**
     * Create an instance of {@link GrupoAtendimentoUnidade }
     * 
     */
    public GrupoAtendimentoUnidade createGrupoAtendimentoUnidade() {
        return new GrupoAtendimentoUnidade();
    }

    /**
     * Create an instance of {@link GrupoAtendimentoOferta }
     * 
     */
    public GrupoAtendimentoOferta createGrupoAtendimentoOferta() {
        return new GrupoAtendimentoOferta();
    }

    /**
     * Create an instance of {@link GrupoAtendimentoDiaSemana }
     * 
     */
    public GrupoAtendimentoDiaSemana createGrupoAtendimentoDiaSemana() {
        return new GrupoAtendimentoDiaSemana();
    }

    /**
     * Create an instance of {@link GrupoAtendimentoSala }
     * 
     */
    public GrupoAtendimentoSala createGrupoAtendimentoSala() {
        return new GrupoAtendimentoSala();
    }

    /**
     * Create an instance of {@link ItemAtendimentoHorarioAula }
     * 
     */
    public ItemAtendimentoHorarioAula createItemAtendimentoHorarioAula() {
        return new ItemAtendimentoHorarioAula();
    }

    /**
     * Create an instance of {@link GrupoAtendimentoTatico }
     * 
     */
    public GrupoAtendimentoTatico createGrupoAtendimentoTatico() {
        return new GrupoAtendimentoTatico();
    }

    /**
     * Create an instance of {@link GrupoIdentificador }
     * 
     */
    public GrupoIdentificador createGrupoIdentificador() {
        return new GrupoIdentificador();
    }

    /**
     * Create an instance of {@link ItemAlunoDemanda }
     * 
     */
    public ItemAlunoDemanda createItemAlunoDemanda() {
        return new ItemAlunoDemanda();
    }

    /**
     * Create an instance of {@link TriedaOutput.RestricoesVioladas.RestricaoViolada }
     * 
     */
    public TriedaOutput.RestricoesVioladas.RestricaoViolada createTriedaOutputRestricoesVioladasRestricaoViolada() {
        return new TriedaOutput.RestricoesVioladas.RestricaoViolada();
    }

}
