package com.gapso.web.trieda.shared.dtos;

import java.util.List;

public interface AtendimentoRelatorioDTO
{
	static public enum ReportType {EXCEL, WEB};
	
	public Long getOfertaId();
	public Long getCampusId();
	public String getCampusString();
	public Integer getSemana();
	public Integer getTotalCreditos();
	public Long getDisciplinaId();
	public String getDisciplinaNome();
	public String getDisciplinaString();
	public Long getDisciplinaSubstitutaId();
	public String getDisciplinaSubstitutaNome();
	public String getDisciplinaSubstitutaString();
	public Long getDisciplinaSubstitutaSemanaLetivaId();
	public Integer getDisciplinaSubstitutaSemanaLetivaTempoAula();
	public String getContentToolTipVisaoSala(ReportType reportType);
	public String getContentToolTipVisaoCurso(ReportType reportType);
	public String getContentToolTipVisaoAluno(ReportType reportType);
	public String getContentVisaoSala(ReportType reportType);
	public String getContentVisaoCurso(ReportType reportType);
	public String getContentVisaoAluno(ReportType reportType);
	public String getQuantidadeAlunosString();
	public Integer getQuantidadeAlunos();
	public String getNomesAlunos();
	public String getTurma();
	public String getCursoNome();
	public String getCursoString();
	public Long getCursoId();
	public String getTurnoString();
	public Long getTurnoId();
	public String getCurriculoString();
	public Long getCurriculoId();
	public Long getSemanaLetivaId();
	public Integer getSemanaLetivaTempoAula();
	public Integer getDuracaoDeUmaAulaEmMinutos();
	public Integer getPeriodo();
	public String getPeriodoString();
	public void concatenateVisaoSala( AtendimentoRelatorioDTO other );
	public void concatenateVisaoCurso( AtendimentoRelatorioDTO other );
	public Long getSalaId();
	public String getSalaString();
	public boolean isTeorico();
	public Integer getTotalCreditoDisciplina();
	public Integer getTotalCreditoDisciplinaSubstituta();
	public String getUnidadeString();
	public boolean isTatico();
	public boolean isProfessorVirtual();
	public Long getProfessorId();
	public Long getProfessorVirtualId();
	public String getProfessorString();
	public String getProfessorVirtualString();
	public String getProfessorCPF();
	public String getProfessorVirtualCPF();
	public Double getProfessorCustoCreditoSemanal();
	public String getCompartilhamentoCursosString();
	public Long getHorarioId();
	public void setCompartilhamentoCursosString( String s );
	public void setCursoNome( String value );
	public void setCurricularString( String value );
	public void setPeriodoString( String value );
	public void setQuantidadeAlunosString( String value );
	public void setQuantidadeAlunos( Integer value );
	public void setNomesAlunos(String nomesAlunos);
	public void setTotalCreditosTeoricosDisciplina(Integer value);
	public Integer getTotalCreditosTeoricosDisciplina();
	public void setTotalCreditosPraticosDisciplina(Integer value);
	public Integer getTotalCreditosPraticosDisciplina();
	public void setDisciplinaUsaLaboratorio(Boolean value);
	public Boolean getDisciplinaUsaLaboratorio();
	public void setQtdDemandaAlunosP1(Integer valye);
	public Integer getQtdDemandaAlunosP1();
	public void setQtdDemandaAlunosP2(Integer valye);
	public Integer getQtdDemandaAlunosP2();
	public void setQtdDemandaAlunosTotal(Integer valye);
	public Integer getQtdDemandaAlunosTotal();
	public void setQuantidadeAlunosP1(Integer value);
	public Integer getQuantidadeAlunosP1();
	public void setQuantidadeAlunosP2(Integer value);
	public Integer getQuantidadeAlunosP2();
	public Integer getDiaSemana();
	
	public List<AlunoDemandaDTO> getAlunosDemandas();
}
